// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID               uuid.UUID
	CustomerID       uuid.UUID
	AccountNumber    string
	TotalBalance     float64
	AvaliableBalance float64
}

type Address struct {
	ID      uuid.UUID
	Street  string
	ZipCode string
	City    string
	State   string
	Country string
}

type Card struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Number          string
	Cvv             string
	ExpirationMonth int32
	ExpirationYear  int32
}

type Customer struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Phone     string
	Status    string
	Cpf       string
	AddressID uuid.UUID
}

type Transaction struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Amount    float64
	Type      string
	Status    string
	CreatedAt pgtype.Timestamp
}
